ProjektZaliczeniowy-S430528/Controllers/FilmLinqController.cs
using ProjektZaliczeniowy_S430528.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProjektZaliczeniowy_S430528.Controllers
{
    [Authorize]
    public class FilmLinqController : Controller
    {
        // GET: Film

        AppDB db = new AppDB();
        public ActionResult Index()
        {
            List<Films> model = db.Films.ToList();
            
            return View(model);
        }

        

    }
}

ProjektZaliczeniowy-S430528/Controllers/FilmsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ProjektZaliczeniowy_S430528.Models;

namespace ProjektZaliczeniowy_S430528.Controllers
{
    [Authorize]
    public class FilmsController : Controller
    {
        private AppDB db = new AppDB();

        // GET: Films
        public ActionResult Index()
        {
            return View(db.Films.ToList());
        }

        // GET: Films/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Films films = db.Films.Find(id);
            if (films == null)
            {
                return HttpNotFound();
            }
            return View(films);
        }

        // GET: Films/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Films/Create
        // Aby zapewnić ochronę przed atakami polegającymi na przesyłaniu dodatkowych danych, włącz określone właściwości, z którymi chcesz utworzyć powiązania.
        // Aby uzyskać więcej szczegółów, zobacz https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "FilmsId,Title,MovieLength,MovieCategory,Director,ReleaseDate")] Films films)
        {
            if (ModelState.IsValid)
            {
                db.Films.Add(films);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(films);
        }

        // GET: Films/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Films films = db.Films.Find(id);
            if (films == null)
            {
                return HttpNotFound();
            }
            return View(films);
        }

        // POST: Films/Edit/5
        // Aby zapewnić ochronę przed atakami polegającymi na przesyłaniu dodatkowych danych, włącz określone właściwości, z którymi chcesz utworzyć powiązania.
        // Aby uzyskać więcej szczegółów, zobacz https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "FilmsId,Title,MovieLength,MovieCategory,Director,ReleaseDate")] Films films)
        {
            if (ModelState.IsValid)
            {
                db.Entry(films).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(films);
        }

        // GET: Films/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Films films = db.Films.Find(id);
            if (films == null)
            {
                return HttpNotFound();
            }
            return View(films);
        }

        // POST: Films/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Films films = db.Films.Find(id);
            db.Films.Remove(films);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ProjektZaliczeniowy-S430528/Views/Shared/_Layout.cshtml
@using Microsoft.AspNet.Identity

    <!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Projekt Zaliczeniowy</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Baza Filmów", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Sprawdź Pogodę", "Pogoda", "Home")</li>
                    <li>@Html.ActionLink("Dodaj Film", "Index", "Films")</li>
                    <li>@Html.ActionLink("Wyświetl Film", "Index", "FilmLinq")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mikołaj Janc - S430528</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>